/*
 * File:           D:\Zoro_DATA\Project\Zeppelin\ADAU1462\DSP-PROJECT\Settings\ADAU1462\ADAU1462_IC_1.h
 *
 * Created:        Monday, November 4, 2019 4:28:49 PM
 * Description:    ADAU1462:IC 1 program data.
 *
 * This software is distributed in the hope that it will be useful,
 * but is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
 * CONDITIONS OF ANY KIND, without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *
 * This software may only be used to program products purchased from
 * Analog Devices for incorporation by you into audio products that
 * are intended for resale to audio product end users. This software
 * may not be distributed whole or in any part to third parties.
 *
 * Copyright ©2019 Analog Devices, Inc. All rights reserved.
 */
#ifndef __ADAU1462_IC_1_H__
#define __ADAU1462_IC_1_H__

#include "SigmaStudioFW.h"
#include "ADAU1462_IC_1_REG.h"

#define DEVICE_ARCHITECTURE_IC_1                  "ADAU1462"
#define DEVICE_ADDR_IC_1                          0x0

/* DSP Program Data */
/* DSP Parameter (Coefficient) Data */

/* Register Default - IC 1.SOFT_RESET */
ADI_REG_TYPE R0_SOFT_RESET_IC_1_Default[REG_SOFT_RESET_IC_1_BYTE] = {
0x00, 0x00
};

/* Register Default - IC 1.SOFT_RESET */
ADI_REG_TYPE R1_SOFT_RESET_IC_1_Default[REG_SOFT_RESET_IC_1_BYTE] = {
0x00, 0x01
};

/* Register Default - IC 1.Reset Delay */
#define R2_RESET_DELAY_IC_1_ADDR 0x0
#define R2_RESET_DELAY_IC_1_SIZE 2
ADI_REG_TYPE R2_RESET_DELAY_IC_1_Default[R2_RESET_DELAY_IC_1_SIZE] = {
0x00, 0xFF
};

/* Register Default - IC 1.HIBERNATE */
ADI_REG_TYPE R3_HIBERNATE_IC_1_Default[REG_HIBERNATE_IC_1_BYTE] = {
0x00, 0x00
};

/* Register Default - IC 1.HIBERNATE */
ADI_REG_TYPE R4_HIBERNATE_IC_1_Default[REG_HIBERNATE_IC_1_BYTE] = {
0x00, 0x01
};

/* Register Default - IC 1.Hibernate Delay */
#define R5_HIBERNATE_DELAY_IC_1_ADDR 0x0
#define R5_HIBERNATE_DELAY_IC_1_SIZE 2
ADI_REG_TYPE R5_HIBERNATE_DELAY_IC_1_Default[R5_HIBERNATE_DELAY_IC_1_SIZE] = {
0x00, 0xFF
};

/* Register Default - IC 1.KILL_CORE */
ADI_REG_TYPE R6_KILL_CORE_IC_1_Default[REG_KILL_CORE_IC_1_BYTE] = {
0x00, 0x00
};

/* Register Default - IC 1.KILL_CORE */
ADI_REG_TYPE R7_KILL_CORE_IC_1_Default[REG_KILL_CORE_IC_1_BYTE] = {
0x00, 0x01
};

/* Register Default - IC 1.PLL_ENABLE */
ADI_REG_TYPE R8_PLL_ENABLE_IC_1_Default[REG_PLL_ENABLE_IC_1_BYTE] = {
0x00, 0x00
};

/* Register Default - IC 1.PLL_CTRL1 Register */
ADI_REG_TYPE R9_PLL_CTRL1_IC_1_Default[REG_PLL_CTRL1_IC_1_BYTE] = {
0x00, 0x02
};

/* Register Default - IC 1.PLL_CLK_SRC Register */
ADI_REG_TYPE R10_PLL_CLK_SRC_IC_1_Default[REG_PLL_CLK_SRC_IC_1_BYTE] = {
0x00, 0x01
};

/* Register Default - IC 1.MCLK_OUT Register */
ADI_REG_TYPE R11_MCLK_OUT_IC_1_Default[REG_MCLK_OUT_IC_1_BYTE] = {
0x00, 0x05
};

/* Register Default - IC 1.PLL_ENABLE Register */
ADI_REG_TYPE R12_PLL_ENABLE_IC_1_Default[REG_PLL_ENABLE_IC_1_BYTE] = {
0x00, 0x01
};

/* Register Default - IC 1.PLL Lock Delay */
#define R13_PLL_LOCK_DELAY_IC_1_ADDR 0x0
#define R13_PLL_LOCK_DELAY_IC_1_SIZE 2
ADI_REG_TYPE R13_PLL_LOCK_DELAY_IC_1_Default[R13_PLL_LOCK_DELAY_IC_1_SIZE] = {
0x00, 0xFF
};

/* Register Default - IC 1.POWER_ENABLE0 Register */
ADI_REG_TYPE R14_POWER_ENABLE0_IC_1_Default[REG_POWER_ENABLE0_IC_1_BYTE] = {
0x1F, 0xFF
};

/* Register Default - IC 1.POWER_ENABLE1 Register */
ADI_REG_TYPE R15_POWER_ENABLE1_IC_1_Default[REG_POWER_ENABLE1_IC_1_BYTE] = {
0x00, 0x1F
};

/* Register Default - IC 1.SOUT_SOURCE0 */
ADI_REG_TYPE R16_SOUT_SOURCE0_IC_1_Default[REG_SOUT_SOURCE0_IC_1_BYTE] = {
0x00, 0x02
};

/* Register Default - IC 1.SOUT_SOURCE1 */
ADI_REG_TYPE R17_SOUT_SOURCE1_IC_1_Default[REG_SOUT_SOURCE1_IC_1_BYTE] = {
0x00, 0x02
};

/* Register Default - IC 1.SOUT_SOURCE2 */
ADI_REG_TYPE R18_SOUT_SOURCE2_IC_1_Default[REG_SOUT_SOURCE2_IC_1_BYTE] = {
0x00, 0x02
};

/* Register Default - IC 1.SOUT_SOURCE3 */
ADI_REG_TYPE R19_SOUT_SOURCE3_IC_1_Default[REG_SOUT_SOURCE3_IC_1_BYTE] = {
0x00, 0x02
};

/* Register Default - IC 1.SOUT_SOURCE4 */
ADI_REG_TYPE R20_SOUT_SOURCE4_IC_1_Default[REG_SOUT_SOURCE4_IC_1_BYTE] = {
0x00, 0x02
};

/* Register Default - IC 1.SOUT_SOURCE5 */
ADI_REG_TYPE R21_SOUT_SOURCE5_IC_1_Default[REG_SOUT_SOURCE5_IC_1_BYTE] = {
0x00, 0x02
};

/* Register Default - IC 1.SOUT_SOURCE6 */
ADI_REG_TYPE R22_SOUT_SOURCE6_IC_1_Default[REG_SOUT_SOURCE6_IC_1_BYTE] = {
0x00, 0x02
};

/* Register Default - IC 1.SOUT_SOURCE7 */
ADI_REG_TYPE R23_SOUT_SOURCE7_IC_1_Default[REG_SOUT_SOURCE7_IC_1_BYTE] = {
0x00, 0x02
};

/* Register Default - IC 1.SOUT_SOURCE8 */
ADI_REG_TYPE R24_SOUT_SOURCE8_IC_1_Default[REG_SOUT_SOURCE8_IC_1_BYTE] = {
0x00, 0x02
};

/* Register Default - IC 1.SOUT_SOURCE9 */
ADI_REG_TYPE R25_SOUT_SOURCE9_IC_1_Default[REG_SOUT_SOURCE9_IC_1_BYTE] = {
0x00, 0x02
};

/* Register Default - IC 1.SOUT_SOURCE10 */
ADI_REG_TYPE R26_SOUT_SOURCE10_IC_1_Default[REG_SOUT_SOURCE10_IC_1_BYTE] = {
0x00, 0x02
};

/* Register Default - IC 1.SOUT_SOURCE11 */
ADI_REG_TYPE R27_SOUT_SOURCE11_IC_1_Default[REG_SOUT_SOURCE11_IC_1_BYTE] = {
0x00, 0x02
};

/* Register Default - IC 1.SOUT_SOURCE12 */
ADI_REG_TYPE R28_SOUT_SOURCE12_IC_1_Default[REG_SOUT_SOURCE12_IC_1_BYTE] = {
0x00, 0x02
};

/* Register Default - IC 1.SOUT_SOURCE13 */
ADI_REG_TYPE R29_SOUT_SOURCE13_IC_1_Default[REG_SOUT_SOURCE13_IC_1_BYTE] = {
0x00, 0x02
};

/* Register Default - IC 1.SOUT_SOURCE14 */
ADI_REG_TYPE R30_SOUT_SOURCE14_IC_1_Default[REG_SOUT_SOURCE14_IC_1_BYTE] = {
0x00, 0x02
};

/* Register Default - IC 1.SOUT_SOURCE15 */
ADI_REG_TYPE R31_SOUT_SOURCE15_IC_1_Default[REG_SOUT_SOURCE15_IC_1_BYTE] = {
0x00, 0x02
};

/* Register Default - IC 1.SOUT_SOURCE16 */
ADI_REG_TYPE R32_SOUT_SOURCE16_IC_1_Default[REG_SOUT_SOURCE16_IC_1_BYTE] = {
0x00, 0x02
};

/* Register Default - IC 1.SOUT_SOURCE17 */
ADI_REG_TYPE R33_SOUT_SOURCE17_IC_1_Default[REG_SOUT_SOURCE17_IC_1_BYTE] = {
0x00, 0x02
};

/* Register Default - IC 1.SOUT_SOURCE18 */
ADI_REG_TYPE R34_SOUT_SOURCE18_IC_1_Default[REG_SOUT_SOURCE18_IC_1_BYTE] = {
0x00, 0x02
};

/* Register Default - IC 1.SOUT_SOURCE19 */
ADI_REG_TYPE R35_SOUT_SOURCE19_IC_1_Default[REG_SOUT_SOURCE19_IC_1_BYTE] = {
0x00, 0x02
};

/* Register Default - IC 1.SOUT_SOURCE20 */
ADI_REG_TYPE R36_SOUT_SOURCE20_IC_1_Default[REG_SOUT_SOURCE20_IC_1_BYTE] = {
0x00, 0x02
};

/* Register Default - IC 1.SOUT_SOURCE21 */
ADI_REG_TYPE R37_SOUT_SOURCE21_IC_1_Default[REG_SOUT_SOURCE21_IC_1_BYTE] = {
0x00, 0x02
};

/* Register Default - IC 1.SOUT_SOURCE22 */
ADI_REG_TYPE R38_SOUT_SOURCE22_IC_1_Default[REG_SOUT_SOURCE22_IC_1_BYTE] = {
0x00, 0x02
};

/* Register Default - IC 1.SOUT_SOURCE23 */
ADI_REG_TYPE R39_SOUT_SOURCE23_IC_1_Default[REG_SOUT_SOURCE23_IC_1_BYTE] = {
0x00, 0x02
};

/* Register Default - IC 1.SERIAL_BYTE_0_1 */
ADI_REG_TYPE R40_SERIAL_BYTE_0_1_IC_1_Default[REG_SERIAL_BYTE_0_1_IC_1_BYTE] = {
0x00, 0x00
};

/* Register Default - IC 1.SERIAL_BYTE_1_1 */
ADI_REG_TYPE R41_SERIAL_BYTE_1_1_IC_1_Default[REG_SERIAL_BYTE_1_1_IC_1_BYTE] = {
0x00, 0x00
};

/* Register Default - IC 1.SERIAL_BYTE_2_1 */
ADI_REG_TYPE R42_SERIAL_BYTE_2_1_IC_1_Default[REG_SERIAL_BYTE_2_1_IC_1_BYTE] = {
0x00, 0x00
};

/* Register Default - IC 1.SERIAL_BYTE_3_1 */
ADI_REG_TYPE R43_SERIAL_BYTE_3_1_IC_1_Default[REG_SERIAL_BYTE_3_1_IC_1_BYTE] = {
0x00, 0x00
};

/* Register Default - IC 1.SERIAL_BYTE_4_0 */
ADI_REG_TYPE R44_SERIAL_BYTE_4_0_IC_1_Default[REG_SERIAL_BYTE_4_0_IC_1_BYTE] = {
0x90, 0x08
};

/* Register Default - IC 1.SERIAL_BYTE_5_0 */
ADI_REG_TYPE R45_SERIAL_BYTE_5_0_IC_1_Default[REG_SERIAL_BYTE_5_0_IC_1_BYTE] = {
0x90, 0x08
};

/* Register Default - IC 1.SERIAL_BYTE_6_0 */
ADI_REG_TYPE R46_SERIAL_BYTE_6_0_IC_1_Default[REG_SERIAL_BYTE_6_0_IC_1_BYTE] = {
0x90, 0x08
};

/* Register Default - IC 1.SERIAL_BYTE_7_0 */
ADI_REG_TYPE R47_SERIAL_BYTE_7_0_IC_1_Default[REG_SERIAL_BYTE_7_0_IC_1_BYTE] = {
0x90, 0x08
};

/* Register Default - IC 1.KILL_CORE */
ADI_REG_TYPE R48_KILL_CORE_IC_1_Default[REG_KILL_CORE_IC_1_BYTE] = {
0x00, 0x00
};

/* Register Default - IC 1.START_ADDRESS */
ADI_REG_TYPE R49_START_ADDRESS_IC_1_Default[REG_START_ADDRESS_IC_1_BYTE] = {
0x00, 0x00
};

/* Register Default - IC 1.START_PULSE */
ADI_REG_TYPE R50_START_PULSE_IC_1_Default[REG_START_PULSE_IC_1_BYTE] = {
0x00, 0x02
};

/* Register Default - IC 1.START_CORE */
ADI_REG_TYPE R51_START_CORE_IC_1_Default[REG_START_CORE_IC_1_BYTE] = {
0x00, 0x00
};

/* Register Default - IC 1.START_CORE */
ADI_REG_TYPE R52_START_CORE_IC_1_Default[REG_START_CORE_IC_1_BYTE] = {
0x00, 0x01
};

/* Register Default - IC 1.Start Delay */
#define R53_START_DELAY_IC_1_ADDR 0x0
#define R53_START_DELAY_IC_1_SIZE 2
ADI_REG_TYPE R53_START_DELAY_IC_1_Default[R53_START_DELAY_IC_1_SIZE] = {
0x00, 0x01
};

/* Register Default - IC 1.HIBERNATE */
ADI_REG_TYPE R54_HIBERNATE_IC_1_Default[REG_HIBERNATE_IC_1_BYTE] = {
0x00, 0x00
};


/*
 * Default Download
 */
#define DEFAULT_DOWNLOAD_SIZE_IC_1 55

void default_download_IC_1() {
	SIGMA_WRITE_REGISTER_BLOCK( DEVICE_ADDR_IC_1, REG_SOFT_RESET_IC_1_ADDR, REG_SOFT_RESET_IC_1_BYTE, R0_SOFT_RESET_IC_1_Default );
	SIGMA_WRITE_REGISTER_BLOCK( DEVICE_ADDR_IC_1, REG_SOFT_RESET_IC_1_ADDR, REG_SOFT_RESET_IC_1_BYTE, R1_SOFT_RESET_IC_1_Default );
	SIGMA_WRITE_DELAY( DEVICE_ADDR_IC_1, R2_RESET_DELAY_IC_1_SIZE, R2_RESET_DELAY_IC_1_Default );
	SIGMA_WRITE_REGISTER_BLOCK( DEVICE_ADDR_IC_1, REG_HIBERNATE_IC_1_ADDR, REG_HIBERNATE_IC_1_BYTE, R3_HIBERNATE_IC_1_Default );
	SIGMA_WRITE_REGISTER_BLOCK( DEVICE_ADDR_IC_1, REG_HIBERNATE_IC_1_ADDR, REG_HIBERNATE_IC_1_BYTE, R4_HIBERNATE_IC_1_Default );
	SIGMA_WRITE_DELAY( DEVICE_ADDR_IC_1, R5_HIBERNATE_DELAY_IC_1_SIZE, R5_HIBERNATE_DELAY_IC_1_Default );
	SIGMA_WRITE_REGISTER_BLOCK( DEVICE_ADDR_IC_1, REG_KILL_CORE_IC_1_ADDR, REG_KILL_CORE_IC_1_BYTE, R6_KILL_CORE_IC_1_Default );
	SIGMA_WRITE_REGISTER_BLOCK( DEVICE_ADDR_IC_1, REG_KILL_CORE_IC_1_ADDR, REG_KILL_CORE_IC_1_BYTE, R7_KILL_CORE_IC_1_Default );
	SIGMA_WRITE_REGISTER_BLOCK( DEVICE_ADDR_IC_1, REG_PLL_ENABLE_IC_1_ADDR, REG_PLL_ENABLE_IC_1_BYTE, R8_PLL_ENABLE_IC_1_Default );
	SIGMA_WRITE_REGISTER_BLOCK( DEVICE_ADDR_IC_1, REG_PLL_CTRL1_IC_1_ADDR, REG_PLL_CTRL1_IC_1_BYTE, R9_PLL_CTRL1_IC_1_Default );
	SIGMA_WRITE_REGISTER_BLOCK( DEVICE_ADDR_IC_1, REG_PLL_CLK_SRC_IC_1_ADDR, REG_PLL_CLK_SRC_IC_1_BYTE, R10_PLL_CLK_SRC_IC_1_Default );
	SIGMA_WRITE_REGISTER_BLOCK( DEVICE_ADDR_IC_1, REG_MCLK_OUT_IC_1_ADDR, REG_MCLK_OUT_IC_1_BYTE, R11_MCLK_OUT_IC_1_Default );
	SIGMA_WRITE_REGISTER_BLOCK( DEVICE_ADDR_IC_1, REG_PLL_ENABLE_IC_1_ADDR, REG_PLL_ENABLE_IC_1_BYTE, R12_PLL_ENABLE_IC_1_Default );
	SIGMA_WRITE_DELAY( DEVICE_ADDR_IC_1, R13_PLL_LOCK_DELAY_IC_1_SIZE, R13_PLL_LOCK_DELAY_IC_1_Default );
	SIGMA_WRITE_REGISTER_BLOCK( DEVICE_ADDR_IC_1, REG_POWER_ENABLE0_IC_1_ADDR, REG_POWER_ENABLE0_IC_1_BYTE, R14_POWER_ENABLE0_IC_1_Default );
	SIGMA_WRITE_REGISTER_BLOCK( DEVICE_ADDR_IC_1, REG_POWER_ENABLE1_IC_1_ADDR, REG_POWER_ENABLE1_IC_1_BYTE, R15_POWER_ENABLE1_IC_1_Default );
	SIGMA_WRITE_REGISTER_BLOCK( DEVICE_ADDR_IC_1, REG_SOUT_SOURCE0_IC_1_ADDR, REG_SOUT_SOURCE0_IC_1_BYTE, R16_SOUT_SOURCE0_IC_1_Default );
	SIGMA_WRITE_REGISTER_BLOCK( DEVICE_ADDR_IC_1, REG_SOUT_SOURCE1_IC_1_ADDR, REG_SOUT_SOURCE1_IC_1_BYTE, R17_SOUT_SOURCE1_IC_1_Default );
	SIGMA_WRITE_REGISTER_BLOCK( DEVICE_ADDR_IC_1, REG_SOUT_SOURCE2_IC_1_ADDR, REG_SOUT_SOURCE2_IC_1_BYTE, R18_SOUT_SOURCE2_IC_1_Default );
	SIGMA_WRITE_REGISTER_BLOCK( DEVICE_ADDR_IC_1, REG_SOUT_SOURCE3_IC_1_ADDR, REG_SOUT_SOURCE3_IC_1_BYTE, R19_SOUT_SOURCE3_IC_1_Default );
	SIGMA_WRITE_REGISTER_BLOCK( DEVICE_ADDR_IC_1, REG_SOUT_SOURCE4_IC_1_ADDR, REG_SOUT_SOURCE4_IC_1_BYTE, R20_SOUT_SOURCE4_IC_1_Default );
	SIGMA_WRITE_REGISTER_BLOCK( DEVICE_ADDR_IC_1, REG_SOUT_SOURCE5_IC_1_ADDR, REG_SOUT_SOURCE5_IC_1_BYTE, R21_SOUT_SOURCE5_IC_1_Default );
	SIGMA_WRITE_REGISTER_BLOCK( DEVICE_ADDR_IC_1, REG_SOUT_SOURCE6_IC_1_ADDR, REG_SOUT_SOURCE6_IC_1_BYTE, R22_SOUT_SOURCE6_IC_1_Default );
	SIGMA_WRITE_REGISTER_BLOCK( DEVICE_ADDR_IC_1, REG_SOUT_SOURCE7_IC_1_ADDR, REG_SOUT_SOURCE7_IC_1_BYTE, R23_SOUT_SOURCE7_IC_1_Default );
	SIGMA_WRITE_REGISTER_BLOCK( DEVICE_ADDR_IC_1, REG_SOUT_SOURCE8_IC_1_ADDR, REG_SOUT_SOURCE8_IC_1_BYTE, R24_SOUT_SOURCE8_IC_1_Default );
	SIGMA_WRITE_REGISTER_BLOCK( DEVICE_ADDR_IC_1, REG_SOUT_SOURCE9_IC_1_ADDR, REG_SOUT_SOURCE9_IC_1_BYTE, R25_SOUT_SOURCE9_IC_1_Default );
	SIGMA_WRITE_REGISTER_BLOCK( DEVICE_ADDR_IC_1, REG_SOUT_SOURCE10_IC_1_ADDR, REG_SOUT_SOURCE10_IC_1_BYTE, R26_SOUT_SOURCE10_IC_1_Default );
	SIGMA_WRITE_REGISTER_BLOCK( DEVICE_ADDR_IC_1, REG_SOUT_SOURCE11_IC_1_ADDR, REG_SOUT_SOURCE11_IC_1_BYTE, R27_SOUT_SOURCE11_IC_1_Default );
	SIGMA_WRITE_REGISTER_BLOCK( DEVICE_ADDR_IC_1, REG_SOUT_SOURCE12_IC_1_ADDR, REG_SOUT_SOURCE12_IC_1_BYTE, R28_SOUT_SOURCE12_IC_1_Default );
	SIGMA_WRITE_REGISTER_BLOCK( DEVICE_ADDR_IC_1, REG_SOUT_SOURCE13_IC_1_ADDR, REG_SOUT_SOURCE13_IC_1_BYTE, R29_SOUT_SOURCE13_IC_1_Default );
	SIGMA_WRITE_REGISTER_BLOCK( DEVICE_ADDR_IC_1, REG_SOUT_SOURCE14_IC_1_ADDR, REG_SOUT_SOURCE14_IC_1_BYTE, R30_SOUT_SOURCE14_IC_1_Default );
	SIGMA_WRITE_REGISTER_BLOCK( DEVICE_ADDR_IC_1, REG_SOUT_SOURCE15_IC_1_ADDR, REG_SOUT_SOURCE15_IC_1_BYTE, R31_SOUT_SOURCE15_IC_1_Default );
	SIGMA_WRITE_REGISTER_BLOCK( DEVICE_ADDR_IC_1, REG_SOUT_SOURCE16_IC_1_ADDR, REG_SOUT_SOURCE16_IC_1_BYTE, R32_SOUT_SOURCE16_IC_1_Default );
	SIGMA_WRITE_REGISTER_BLOCK( DEVICE_ADDR_IC_1, REG_SOUT_SOURCE17_IC_1_ADDR, REG_SOUT_SOURCE17_IC_1_BYTE, R33_SOUT_SOURCE17_IC_1_Default );
	SIGMA_WRITE_REGISTER_BLOCK( DEVICE_ADDR_IC_1, REG_SOUT_SOURCE18_IC_1_ADDR, REG_SOUT_SOURCE18_IC_1_BYTE, R34_SOUT_SOURCE18_IC_1_Default );
	SIGMA_WRITE_REGISTER_BLOCK( DEVICE_ADDR_IC_1, REG_SOUT_SOURCE19_IC_1_ADDR, REG_SOUT_SOURCE19_IC_1_BYTE, R35_SOUT_SOURCE19_IC_1_Default );
	SIGMA_WRITE_REGISTER_BLOCK( DEVICE_ADDR_IC_1, REG_SOUT_SOURCE20_IC_1_ADDR, REG_SOUT_SOURCE20_IC_1_BYTE, R36_SOUT_SOURCE20_IC_1_Default );
	SIGMA_WRITE_REGISTER_BLOCK( DEVICE_ADDR_IC_1, REG_SOUT_SOURCE21_IC_1_ADDR, REG_SOUT_SOURCE21_IC_1_BYTE, R37_SOUT_SOURCE21_IC_1_Default );
	SIGMA_WRITE_REGISTER_BLOCK( DEVICE_ADDR_IC_1, REG_SOUT_SOURCE22_IC_1_ADDR, REG_SOUT_SOURCE22_IC_1_BYTE, R38_SOUT_SOURCE22_IC_1_Default );
	SIGMA_WRITE_REGISTER_BLOCK( DEVICE_ADDR_IC_1, REG_SOUT_SOURCE23_IC_1_ADDR, REG_SOUT_SOURCE23_IC_1_BYTE, R39_SOUT_SOURCE23_IC_1_Default );
	SIGMA_WRITE_REGISTER_BLOCK( DEVICE_ADDR_IC_1, REG_SERIAL_BYTE_0_1_IC_1_ADDR, REG_SERIAL_BYTE_0_1_IC_1_BYTE, R40_SERIAL_BYTE_0_1_IC_1_Default );
	SIGMA_WRITE_REGISTER_BLOCK( DEVICE_ADDR_IC_1, REG_SERIAL_BYTE_1_1_IC_1_ADDR, REG_SERIAL_BYTE_1_1_IC_1_BYTE, R41_SERIAL_BYTE_1_1_IC_1_Default );
	SIGMA_WRITE_REGISTER_BLOCK( DEVICE_ADDR_IC_1, REG_SERIAL_BYTE_2_1_IC_1_ADDR, REG_SERIAL_BYTE_2_1_IC_1_BYTE, R42_SERIAL_BYTE_2_1_IC_1_Default );
	SIGMA_WRITE_REGISTER_BLOCK( DEVICE_ADDR_IC_1, REG_SERIAL_BYTE_3_1_IC_1_ADDR, REG_SERIAL_BYTE_3_1_IC_1_BYTE, R43_SERIAL_BYTE_3_1_IC_1_Default );
	SIGMA_WRITE_REGISTER_BLOCK( DEVICE_ADDR_IC_1, REG_SERIAL_BYTE_4_0_IC_1_ADDR, REG_SERIAL_BYTE_4_0_IC_1_BYTE, R44_SERIAL_BYTE_4_0_IC_1_Default );
	SIGMA_WRITE_REGISTER_BLOCK( DEVICE_ADDR_IC_1, REG_SERIAL_BYTE_5_0_IC_1_ADDR, REG_SERIAL_BYTE_5_0_IC_1_BYTE, R45_SERIAL_BYTE_5_0_IC_1_Default );
	SIGMA_WRITE_REGISTER_BLOCK( DEVICE_ADDR_IC_1, REG_SERIAL_BYTE_6_0_IC_1_ADDR, REG_SERIAL_BYTE_6_0_IC_1_BYTE, R46_SERIAL_BYTE_6_0_IC_1_Default );
	SIGMA_WRITE_REGISTER_BLOCK( DEVICE_ADDR_IC_1, REG_SERIAL_BYTE_7_0_IC_1_ADDR, REG_SERIAL_BYTE_7_0_IC_1_BYTE, R47_SERIAL_BYTE_7_0_IC_1_Default );
	SIGMA_WRITE_REGISTER_BLOCK( DEVICE_ADDR_IC_1, REG_KILL_CORE_IC_1_ADDR, REG_KILL_CORE_IC_1_BYTE, R48_KILL_CORE_IC_1_Default );
	SIGMA_WRITE_REGISTER_BLOCK( DEVICE_ADDR_IC_1, REG_START_ADDRESS_IC_1_ADDR, REG_START_ADDRESS_IC_1_BYTE, R49_START_ADDRESS_IC_1_Default );
	SIGMA_WRITE_REGISTER_BLOCK( DEVICE_ADDR_IC_1, REG_START_PULSE_IC_1_ADDR, REG_START_PULSE_IC_1_BYTE, R50_START_PULSE_IC_1_Default );
	SIGMA_WRITE_REGISTER_BLOCK( DEVICE_ADDR_IC_1, REG_START_CORE_IC_1_ADDR, REG_START_CORE_IC_1_BYTE, R51_START_CORE_IC_1_Default );
	SIGMA_WRITE_REGISTER_BLOCK( DEVICE_ADDR_IC_1, REG_START_CORE_IC_1_ADDR, REG_START_CORE_IC_1_BYTE, R52_START_CORE_IC_1_Default );
	SIGMA_WRITE_DELAY( DEVICE_ADDR_IC_1, R53_START_DELAY_IC_1_SIZE, R53_START_DELAY_IC_1_Default );
	SIGMA_WRITE_REGISTER_BLOCK( DEVICE_ADDR_IC_1, REG_HIBERNATE_IC_1_ADDR, REG_HIBERNATE_IC_1_BYTE, R54_HIBERNATE_IC_1_Default );
}

#endif
